all: encoder

encoder: util.o start.o task1b.o
	ld -m elf_i386 start.o task1b.o util.o -o encoder

util.o : util.c
	gcc -m32 -Wall -ansi -c -nostdlib -fno-stack-protector util.c -o util.o

task1b.o : task1b.c
	gcc -m32 -Wall -ansi -c -nostdlib -fno-stack-protector task1b.c -o task1b.o

start.o : start.s
	nasm -f elf start.s -o start.o

.PHONY: clean

clean:
	rm -f *.o encoder